### ISSUE TITLE
tkinter.TclErr

### ISSUE THREAD

**Issue by brandonlampe** [breedlun/clearplot#3] opened 2016-03-07 02:29 UTC
Ben... I tried running your 'bare_bones' example and the following error message was returned.  This may be specific to my machine, not sure.  Regardless, I thought I'd pass it on.

I installed clearplot via pip, my os is OSX Yosemite, and I'm running python via SublimeText3.

Cheers,
Brandon

objc[43950]: Class TKApplication is implemented in both /Users/Lampe/anaconda/lib/libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[43950]: Class TKMenu is implemented in both /Users/Lampe/anaconda/lib/libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[43950]: Class TKContentView is implemented in both /Users/Lampe/anaconda/lib/libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
objc[43950]: Class TKWindow is implemented in both /Users/Lampe/anaconda/lib/libtk8.5.dylib and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
2016-03-06 19:20:58.494 python[43950:2589562] setCanCycle: is deprecated.  Please use setCollectionBehavior instead
Traceback (most recent call last):
  File "/Users/Lampe/PyScripts/surgeAnalysis/WaveEqn_InfBarAnn.py", line 138, in <module>
    pf.plot('test_clearplot',x,y)
  File "/usr/local/lib/python2.7/site-packages/clearplot/plot_functions.py", line 161, in plot
    fig.auto_adjust_layout()
  File "/usr/local/lib/python2.7/site-packages/clearplot/figure.py", line 457, in auto_adjust_layout
    fig_bbox = self.tight_bbox
  File "/usr/local/lib/python2.7/site-packages/clearplot/figure.py", line 102, in tight_bbox
    self.draw()
  File "/usr/local/lib/python2.7/site-packages/clearplot/figure.py", line 486, in draw
    self.mpl_fig.canvas.draw()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 355, in draw
    tkagg.blit(self._tkphoto, self.renderer._renderer, colormode=2)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 30, in blit
    id(data), colormode, id(bbox_array))
_tkinter.TclError
[Finished in 0.8s with exit code 1]
[shell_cmd: python -u "/Users/Lampe/PyScripts/surgeAnalysis/WaveEqn_InfBarAnn.py"]
[dir: /Users/Lampe/PyScripts/surgeAnalysis]
[path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/opt/ImageMagick/bin:/usr/texbin:/Users/Lampe/anaconda/bin:/Users/Lampe/PyScripts:/Applications/Julia-0.4.0.app/Contents/Resources/julia/bin/]

**Comment by breedlun** [comment] 2016-03-07 03:02
Hmmm...  This might be to tough to troubleshoot since it does not occur on my machine.  I am running Enthought Canopy on OS X 10.8 at home and Enthought Canopy on OS X 10.10 at work.  It looks like you are on Anaconda.  

I suspect the issue is not actually clearplot, but something wrong with your Tkinter installation or your matplotlib installation.  Can you try to create a plot using the TkAgg backend in plain matplotlib?  To do so, fire up a python interpreter on the command line and do the following
    
    import matplotlib as mpl
    mpl.rcParams['backend'] = 'TkAgg'
    import matplotlib.pyplot as plt
    plt.plot([0,1], [0,1])
    plt.show()

If this works, you should get a window that pops up with a simple plot in it.  If it fails, then quit out of the python interpreter (control-D), and repeat the process with the `'MacOSX'` backend.  Let me know what you find.

**Comment by brandonlampe** [comment] 2016-03-07 03:26
I get an error when I try import pyplot (see below).  

I used time machine and returned to pre "pip install clearplot", and the commands ran fine.  Looks like this post addresses the issue:
http://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python

'''
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/site-packages/matplotlib/externals/six.py", line 199, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named _tkinter
'''

**Comment by brandonlampe** [comment] 2016-03-07 03:33
And your script worked fine when I used the  'MacOSX' backend

**Comment by breedlun** [comment] 2016-03-07 03:36
Oh, man.  That's really strange that installing clearplot ruins your Tkinter/matplotlib installation.  Clearplot installs a couple fonts into matplotlib, but other than that, it doesn't touch your matplotlib installation.  

I think the stackoverflow post you found is something different.  They resolved the issue by switching to the TkAgg backend, whereas your problem is the TkAgg backend.

**Comment by breedlun** [comment] 2016-03-07 03:39
Your issue seems more similar to [this post](http://stackoverflow.com/questions/34405087/why-is-pyplot-giving-me-a-tclerror-on-osx), but it doesn't looks like they came up with a solution.

**Comment by brandonlampe** [comment] 2016-03-07 03:47
yep... I think your correct

**Comment by breedlun** [comment] 2016-03-07 03:52
Here is another [post](http://stackoverflow.com/questions/35145314/tclerror-matplotlib-1-5-0) detailing a similar issue.  

Are you absolutely certain you can get the TkAgg backend to work pre-clearplot?  Can you humor me, and rerun

    import matplotlib as mpl
    mpl.use('TkAgg')
    import matplotlib.pyplot as plt
    plt.plot([0,1], [0,1])
    plt.show()

on your pre-clearplot setup?  (It is important to specify the backend before you import pyplot.)  It seems like it shouldn't work.

A possible work around is to use the 'Qt4Agg' backend instead of 'TkAgg'.  I ran into some issues with matplotlib 1.5.0 and the 'Qt4Agg' backend, but they seem to be resolved with matplotlib 1.5.1.

**Comment by brandonlampe** [comment] 2016-03-07 04:03
I went back to pre-clearplot and ran it with the TkAgg... everything wen through fine.

**Comment by breedlun** [comment] 2016-03-07 04:10
So bizarre…  I know of one other guy who I think uses Anaconda with clearplot.  Let me verify.

**Comment by breedlun** [comment] 2016-05-15 22:28
Well, I checked with the other guy who uses Anaconda with clearplot, and he does not have any issues with the TkAgg backend.  I am going to close this issue since I cannot recreate it.  Feel free to reopen it if anything new turns up.

**Closed by breedlun** 2016-05-15 22:28 UTC
